version: "3.8"

services:
  admin-web:
    build:
      context: .
      dockerfile: admin-web/Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8081}
    ports:
      - "3000:3000"

  customer-web:
    build:
      context: .
      dockerfile: customer-web/Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8081}
    ports:
      - "3001:3000"
